jenkins:
  build: ./01-custom-jenkins
  ports:
   - "8080:8080"
  volumes:
   - /volumes/jenkins:/var/jenkins_home
   - /var/run/docker.sock:/var/run/docker.sock
  container_name: traineegrp-jenkins
  privileged: true
  links:
  - sonar
  - nexus
  - elk

nexus:
  image: "sonatype/nexus:2.11.2-06"
  ports:
   - "8081:8081"
  volumes:
   - /volumes/nexus:/sonatype-work
  container_name: traineegrp-nexus
  links:
  - elk
 
sonar:
  image: "sonarqube:5.2"
  ports:
   - "9000:9000"
   - "9092:9092"
  container_name: traineegrp-sonarqube
  volumes:
   - /volumes/sonar/data:/opt/sonarqube/data
   - /volumes/sonar/extensions:/opt/sonarqube/extensions
  links:
   - elk

elk:
  image: "sebp/elk:E1L1K4"
  ports:
   - "9200:9200"
   - "5601:5601"
  volumes: 
   - /volumes/elk:/var/lib/elasticsearch
  container_name: traineegrp-elk
