jenkins:
  build: ./01-custom-jenkins
  ports:
   - "808${TRAINEEGRPID}:8080"
   - "500${TRAINEEGRPID}:5000"
  volumes:
   - /volumes/jenkins/traineegrp${TRAINEEGRPID}-jenkins:/var/jenkins_home
   - /var/run/docker.sock:/var/run/docker.sock
  container_name: traineegrp${TRAINEEGRPID}-jenkins
  privileged: true
  links:
  - sonar
  - nexus
  - elk

nexus:
  image: "sonatype/nexus:2.11.2-06"
  ports:
   - "809${TRAINEEGRPID}:8081"
  volumes:
   - /volumes/nexus/traineegrp${TRAINEEGRPID}-nexus:/sonatype-work
  container_name: traineegrp${TRAINEEGRPID}-nexus
  links:
  - elk
 
sonar:
  image: "sonarqube:5.2"
  ports:
   - "900${TRAINEEGRPID}:9000"
   - "901${TRAINEEGRPID}:9092"
  container_name: traineegrp${TRAINEEGRPID}-sonarqube
  links:
   - elk

elk:
  image: "sebp/elk:E1L1K4"
  ports:
   - "920${TRAINEEGRPID}:9200"
   - "930${TRAINEEGRPID}:9300"
   - "560${TRAINEEGRPID}:5601"
  volumes: 
   - /volumes/elk/traineegrp${TRAINEEGRPID}-elk:/var/lib/elasticsearch
  container_name: traineegrp${TRAINEEGRPID}-elk
